name: test
on:
  push: {branches: [master]}
  pull_request: {branches: [master]}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '29.1'
          - 'snapshot'
        include:
          - emacs_version: 'snapshot'
            allow_failure: true
    steps:
    - name: Install zsh
      run: "sudo apt-get install -y zsh && zsh --version"

    - name: Install fish
      run: "sudo brew install -q fish && fish --version"

    - uses: actions/checkout@v1
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master

    - name: Run tests
      if: matrix.allow_failure != true
      run: 'cask && make test'

    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: 'cask && make test || true'
      
